######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 12 16:33:16 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += recurse.cpp
