/********************************************************************************
** Form generated from reading UI file 'catan_map.ui'
**
** Created: Sun Apr 8 18:48:03 2012
**      by: Qt User Interface Compiler version 4.7.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CATAN_MAP_H
#define UI_CATAN_MAP_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QMainWindow>
#include <QtGui/QMenu>
#include <QtGui/QMenuBar>
#include <QtGui/QPushButton>
#include <QtGui/QStatusBar>
#include <QtGui/QToolBar>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_catan_map
{
public:
    QAction *actionWorks;
    QWidget *centralWidget;
    QLabel *image_label;
    QPushButton *pushButton_01;
    QPushButton *pushButton_02;
    QPushButton *pushButton_03;
    QPushButton *pushButton_04;
    QPushButton *pushButton_05;
    QPushButton *pushButton_06;
    QPushButton *pushButton_07;
    QPushButton *pushButton_08;
    QPushButton *pushButton_09;
    QPushButton *pushButton_10;
    QPushButton *pushButton_11;
    QPushButton *pushButton_14;
    QPushButton *pushButton_13;
    QPushButton *pushButton_12;
    QPushButton *pushButton_17;
    QPushButton *pushButton_18;
    QPushButton *pushButton_16;
    QPushButton *pushButton_15;
    QPushButton *pushButton_19;
    QPushButton *pushButton_20;
    QPushButton *pushButton_21;
    QPushButton *pushButton_22;
    QPushButton *pushButton_23;
    QPushButton *pushButton_050;
    QPushButton *pushButton_24;
    QPushButton *pushButton_25;
    QPushButton *pushButton_26;
    QPushButton *pushButton_27;
    QPushButton *pushButton_28;
    QPushButton *pushButton_29;
    QPushButton *pushButton_30;
    QPushButton *pushButton_31;
    QPushButton *pushButton_32;
    QPushButton *pushButton_33;
    QPushButton *pushButton_34;
    QPushButton *pushButton_35;
    QPushButton *pushButton_36;
    QPushButton *pushButton_37;
    QPushButton *pushButton_43;
    QPushButton *pushButton_45;
    QPushButton *pushButton_44;
    QPushButton *pushButton_41;
    QPushButton *pushButton_42;
    QPushButton *pushButton_40;
    QPushButton *pushButton_49;
    QPushButton *pushButton_46;
    QPushButton *pushButton_39;
    QPushButton *pushButton_38;
    QPushButton *pushButton_47;
    QPushButton *pushButton_48;
    QPushButton *pushButton_50;
    QPushButton *pushButton_51;
    QPushButton *pushButton_52;
    QPushButton *pushButton_53;
    QPushButton *pushRoad_01;
    QPushButton *pushRoad_02;
    QPushButton *pushRoad_15;
    QPushButton *pushRoad_03;
    QPushButton *pushRoad_04;
    QPushButton *pushRoad_05;
    QPushButton *pushRoad_06;
    QPushButton *pushRoad_07;
    QPushButton *pushRoad_08;
    QPushButton *pushRoad_09;
    QPushButton *pushRoad_10;
    QPushButton *pushRoad_11;
    QPushButton *pushRoad_12;
    QPushButton *pushRoad_13;
    QPushButton *pushRoad_14;
    QPushButton *pushRoad_16;
    QPushButton *pushRoad_17;
    QPushButton *pushRoad_18;
    QPushButton *pushRoad_19;
    QPushButton *pushRoad_20;
    QPushButton *pushRoad_21;
    QPushButton *pushRoad_22;
    QPushButton *pushRoad_23;
    QPushButton *pushRoad_24;
    QPushButton *pushRoad_25;
    QPushButton *pushRoad_26;
    QPushButton *pushRoad_27;
    QPushButton *pushRoad_28;
    QPushButton *pushRoad_29;
    QPushButton *pushRoad_30;
    QPushButton *pushRoad_31;
    QPushButton *pushRoad_32;
    QPushButton *pushRoad_33;
    QPushButton *pushRoad_34;
    QPushButton *pushRoad_35;
    QPushButton *pushRoad_36;
    QPushButton *pushRoad_37;
    QPushButton *pushRoad_38;
    QPushButton *pushRoad_39;
    QPushButton *pushRoad_40;
    QPushButton *pushRoad_41;
    QPushButton *pushRoad_42;
    QPushButton *pushRoad_43;
    QPushButton *pushRoad_44;
    QPushButton *pushRoad_45;
    QPushButton *pushRoad_46;
    QPushButton *pushRoad_47;
    QPushButton *pushRoad_48;
    QPushButton *pushRoad_49;
    QPushButton *pushRoad_50;
    QPushButton *pushRoad_51;
    QPushButton *pushRoad_52;
    QPushButton *pushRoad_53;
    QPushButton *pushRoad_54;
    QPushButton *pushRoad_55;
    QPushButton *pushRoad_56;
    QPushButton *pushRoad_57;
    QPushButton *pushRoad_58;
    QPushButton *pushRoad_59;
    QPushButton *pushRoad_60;
    QPushButton *pushRoad_61;
    QPushButton *pushRoad_62;
    QPushButton *pushRoad_63;
    QPushButton *pushRoad_64;
    QPushButton *pushRoad_65;
    QPushButton *pushRoad_66;
    QPushButton *pushRoad_67;
    QPushButton *pushRoad_68;
    QPushButton *pushRoad_69;
    QPushButton *pushRoad_70;
    QPushButton *pushRoad_71;
    QPushButton *pushRoad_72;
    QMenuBar *menuBar;
    QMenu *menuSample;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *catan_map)
    {
        if (catan_map->objectName().isEmpty())
            catan_map->setObjectName(QString::fromUtf8("catan_map"));
        catan_map->resize(1000, 703);
        actionWorks = new QAction(catan_map);
        actionWorks->setObjectName(QString::fromUtf8("actionWorks"));
        centralWidget = new QWidget(catan_map);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        image_label = new QLabel(centralWidget);
        image_label->setObjectName(QString::fromUtf8("image_label"));
        image_label->setGeometry(QRect(0, 0, 800, 600));
        pushButton_01 = new QPushButton(centralWidget);
        pushButton_01->setObjectName(QString::fromUtf8("pushButton_01"));
        pushButton_01->setGeometry(QRect(255, 30, 21, 21));
        pushButton_02 = new QPushButton(centralWidget);
        pushButton_02->setObjectName(QString::fromUtf8("pushButton_02"));
        pushButton_02->setGeometry(QRect(313, 128, 21, 21));
        pushButton_03 = new QPushButton(centralWidget);
        pushButton_03->setObjectName(QString::fromUtf8("pushButton_03"));
        pushButton_03->setGeometry(QRect(200, 128, 21, 21));
        pushButton_04 = new QPushButton(centralWidget);
        pushButton_04->setObjectName(QString::fromUtf8("pushButton_04"));
        pushButton_04->setGeometry(QRect(200, 68, 21, 21));
        pushButton_05 = new QPushButton(centralWidget);
        pushButton_05->setObjectName(QString::fromUtf8("pushButton_05"));
        pushButton_05->setGeometry(QRect(255, 162, 21, 21));
        pushButton_06 = new QPushButton(centralWidget);
        pushButton_06->setObjectName(QString::fromUtf8("pushButton_06"));
        pushButton_06->setGeometry(QRect(313, 68, 21, 21));
        pushButton_07 = new QPushButton(centralWidget);
        pushButton_07->setObjectName(QString::fromUtf8("pushButton_07"));
        pushButton_07->setGeometry(QRect(426, 68, 21, 21));
        pushButton_08 = new QPushButton(centralWidget);
        pushButton_08->setObjectName(QString::fromUtf8("pushButton_08"));
        pushButton_08->setGeometry(QRect(368, 162, 21, 21));
        pushButton_09 = new QPushButton(centralWidget);
        pushButton_09->setObjectName(QString::fromUtf8("pushButton_09"));
        pushButton_09->setGeometry(QRect(368, 30, 21, 21));
        pushButton_10 = new QPushButton(centralWidget);
        pushButton_10->setObjectName(QString::fromUtf8("pushButton_10"));
        pushButton_10->setGeometry(QRect(426, 128, 21, 21));
        pushButton_11 = new QPushButton(centralWidget);
        pushButton_11->setObjectName(QString::fromUtf8("pushButton_11"));
        pushButton_11->setGeometry(QRect(481, 30, 21, 21));
        pushButton_14 = new QPushButton(centralWidget);
        pushButton_14->setObjectName(QString::fromUtf8("pushButton_14"));
        pushButton_14->setGeometry(QRect(481, 162, 21, 21));
        pushButton_13 = new QPushButton(centralWidget);
        pushButton_13->setObjectName(QString::fromUtf8("pushButton_13"));
        pushButton_13->setGeometry(QRect(539, 68, 21, 21));
        pushButton_12 = new QPushButton(centralWidget);
        pushButton_12->setObjectName(QString::fromUtf8("pushButton_12"));
        pushButton_12->setGeometry(QRect(539, 128, 21, 21));
        pushButton_17 = new QPushButton(centralWidget);
        pushButton_17->setObjectName(QString::fromUtf8("pushButton_17"));
        pushButton_17->setGeometry(QRect(142, 162, 21, 21));
        pushButton_18 = new QPushButton(centralWidget);
        pushButton_18->setObjectName(QString::fromUtf8("pushButton_18"));
        pushButton_18->setGeometry(QRect(200, 260, 21, 21));
        pushButton_16 = new QPushButton(centralWidget);
        pushButton_16->setObjectName(QString::fromUtf8("pushButton_16"));
        pushButton_16->setGeometry(QRect(142, 222, 21, 21));
        pushButton_15 = new QPushButton(centralWidget);
        pushButton_15->setObjectName(QString::fromUtf8("pushButton_15"));
        pushButton_15->setGeometry(QRect(255, 222, 21, 21));
        pushButton_19 = new QPushButton(centralWidget);
        pushButton_19->setObjectName(QString::fromUtf8("pushButton_19"));
        pushButton_19->setGeometry(QRect(594, 222, 21, 21));
        pushButton_20 = new QPushButton(centralWidget);
        pushButton_20->setObjectName(QString::fromUtf8("pushButton_20"));
        pushButton_20->setGeometry(QRect(368, 222, 21, 21));
        pushButton_21 = new QPushButton(centralWidget);
        pushButton_21->setObjectName(QString::fromUtf8("pushButton_21"));
        pushButton_21->setGeometry(QRect(481, 222, 21, 21));
        pushButton_22 = new QPushButton(centralWidget);
        pushButton_22->setObjectName(QString::fromUtf8("pushButton_22"));
        pushButton_22->setGeometry(QRect(594, 162, 21, 21));
        pushButton_23 = new QPushButton(centralWidget);
        pushButton_23->setObjectName(QString::fromUtf8("pushButton_23"));
        pushButton_23->setGeometry(QRect(539, 260, 21, 21));
        pushButton_050 = new QPushButton(centralWidget);
        pushButton_050->setObjectName(QString::fromUtf8("pushButton_050"));
        pushButton_050->setGeometry(QRect(313, 260, 21, 21));
        pushButton_24 = new QPushButton(centralWidget);
        pushButton_24->setObjectName(QString::fromUtf8("pushButton_24"));
        pushButton_24->setGeometry(QRect(426, 260, 21, 21));
        pushButton_25 = new QPushButton(centralWidget);
        pushButton_25->setObjectName(QString::fromUtf8("pushButton_25"));
        pushButton_25->setGeometry(QRect(87, 260, 21, 21));
        pushButton_26 = new QPushButton(centralWidget);
        pushButton_26->setObjectName(QString::fromUtf8("pushButton_26"));
        pushButton_26->setGeometry(QRect(142, 354, 21, 21));
        pushButton_27 = new QPushButton(centralWidget);
        pushButton_27->setObjectName(QString::fromUtf8("pushButton_27"));
        pushButton_27->setGeometry(QRect(87, 320, 21, 21));
        pushButton_28 = new QPushButton(centralWidget);
        pushButton_28->setObjectName(QString::fromUtf8("pushButton_28"));
        pushButton_28->setGeometry(QRect(200, 320, 21, 21));
        pushButton_29 = new QPushButton(centralWidget);
        pushButton_29->setObjectName(QString::fromUtf8("pushButton_29"));
        pushButton_29->setGeometry(QRect(426, 320, 21, 21));
        pushButton_30 = new QPushButton(centralWidget);
        pushButton_30->setObjectName(QString::fromUtf8("pushButton_30"));
        pushButton_30->setGeometry(QRect(313, 320, 21, 21));
        pushButton_31 = new QPushButton(centralWidget);
        pushButton_31->setObjectName(QString::fromUtf8("pushButton_31"));
        pushButton_31->setGeometry(QRect(539, 320, 21, 21));
        pushButton_32 = new QPushButton(centralWidget);
        pushButton_32->setObjectName(QString::fromUtf8("pushButton_32"));
        pushButton_32->setGeometry(QRect(652, 320, 21, 21));
        pushButton_33 = new QPushButton(centralWidget);
        pushButton_33->setObjectName(QString::fromUtf8("pushButton_33"));
        pushButton_33->setGeometry(QRect(652, 260, 21, 21));
        pushButton_34 = new QPushButton(centralWidget);
        pushButton_34->setObjectName(QString::fromUtf8("pushButton_34"));
        pushButton_34->setGeometry(QRect(255, 354, 21, 21));
        pushButton_35 = new QPushButton(centralWidget);
        pushButton_35->setObjectName(QString::fromUtf8("pushButton_35"));
        pushButton_35->setGeometry(QRect(368, 354, 21, 21));
        pushButton_36 = new QPushButton(centralWidget);
        pushButton_36->setObjectName(QString::fromUtf8("pushButton_36"));
        pushButton_36->setGeometry(QRect(481, 354, 21, 21));
        pushButton_37 = new QPushButton(centralWidget);
        pushButton_37->setObjectName(QString::fromUtf8("pushButton_37"));
        pushButton_37->setGeometry(QRect(594, 354, 21, 21));
        pushButton_43 = new QPushButton(centralWidget);
        pushButton_43->setObjectName(QString::fromUtf8("pushButton_43"));
        pushButton_43->setGeometry(QRect(255, 414, 21, 21));
        pushButton_45 = new QPushButton(centralWidget);
        pushButton_45->setObjectName(QString::fromUtf8("pushButton_45"));
        pushButton_45->setGeometry(QRect(368, 414, 21, 21));
        pushButton_44 = new QPushButton(centralWidget);
        pushButton_44->setObjectName(QString::fromUtf8("pushButton_44"));
        pushButton_44->setGeometry(QRect(594, 414, 21, 21));
        pushButton_41 = new QPushButton(centralWidget);
        pushButton_41->setObjectName(QString::fromUtf8("pushButton_41"));
        pushButton_41->setGeometry(QRect(426, 452, 21, 21));
        pushButton_42 = new QPushButton(centralWidget);
        pushButton_42->setObjectName(QString::fromUtf8("pushButton_42"));
        pushButton_42->setGeometry(QRect(539, 452, 21, 21));
        pushButton_40 = new QPushButton(centralWidget);
        pushButton_40->setObjectName(QString::fromUtf8("pushButton_40"));
        pushButton_40->setGeometry(QRect(142, 414, 21, 21));
        pushButton_49 = new QPushButton(centralWidget);
        pushButton_49->setObjectName(QString::fromUtf8("pushButton_49"));
        pushButton_49->setGeometry(QRect(313, 452, 21, 21));
        pushButton_46 = new QPushButton(centralWidget);
        pushButton_46->setObjectName(QString::fromUtf8("pushButton_46"));
        pushButton_46->setGeometry(QRect(481, 414, 21, 21));
        pushButton_39 = new QPushButton(centralWidget);
        pushButton_39->setObjectName(QString::fromUtf8("pushButton_39"));
        pushButton_39->setGeometry(QRect(200, 452, 21, 21));
        pushButton_38 = new QPushButton(centralWidget);
        pushButton_38->setObjectName(QString::fromUtf8("pushButton_38"));
        pushButton_38->setGeometry(QRect(368, 546, 21, 21));
        pushButton_47 = new QPushButton(centralWidget);
        pushButton_47->setObjectName(QString::fromUtf8("pushButton_47"));
        pushButton_47->setGeometry(QRect(481, 546, 21, 21));
        pushButton_48 = new QPushButton(centralWidget);
        pushButton_48->setObjectName(QString::fromUtf8("pushButton_48"));
        pushButton_48->setGeometry(QRect(539, 512, 21, 21));
        pushButton_50 = new QPushButton(centralWidget);
        pushButton_50->setObjectName(QString::fromUtf8("pushButton_50"));
        pushButton_50->setGeometry(QRect(426, 512, 21, 21));
        pushButton_51 = new QPushButton(centralWidget);
        pushButton_51->setObjectName(QString::fromUtf8("pushButton_51"));
        pushButton_51->setGeometry(QRect(255, 546, 21, 21));
        pushButton_52 = new QPushButton(centralWidget);
        pushButton_52->setObjectName(QString::fromUtf8("pushButton_52"));
        pushButton_52->setGeometry(QRect(200, 512, 21, 21));
        pushButton_53 = new QPushButton(centralWidget);
        pushButton_53->setObjectName(QString::fromUtf8("pushButton_53"));
        pushButton_53->setGeometry(QRect(313, 512, 21, 21));
        pushRoad_01 = new QPushButton(centralWidget);
        pushRoad_01->setObjectName(QString::fromUtf8("pushRoad_01"));
        pushRoad_01->setGeometry(QRect(200, 93, 21, 31));
        pushRoad_02 = new QPushButton(centralWidget);
        pushRoad_02->setObjectName(QString::fromUtf8("pushRoad_02"));
        pushRoad_02->setGeometry(QRect(313, 93, 21, 31));
        pushRoad_15 = new QPushButton(centralWidget);
        pushRoad_15->setObjectName(QString::fromUtf8("pushRoad_15"));
        pushRoad_15->setGeometry(QRect(87, 285, 21, 31));
        pushRoad_03 = new QPushButton(centralWidget);
        pushRoad_03->setObjectName(QString::fromUtf8("pushRoad_03"));
        pushRoad_03->setGeometry(QRect(200, 285, 21, 31));
        pushRoad_04 = new QPushButton(centralWidget);
        pushRoad_04->setObjectName(QString::fromUtf8("pushRoad_04"));
        pushRoad_04->setGeometry(QRect(200, 477, 21, 31));
        pushRoad_05 = new QPushButton(centralWidget);
        pushRoad_05->setObjectName(QString::fromUtf8("pushRoad_05"));
        pushRoad_05->setGeometry(QRect(313, 285, 21, 31));
        pushRoad_06 = new QPushButton(centralWidget);
        pushRoad_06->setObjectName(QString::fromUtf8("pushRoad_06"));
        pushRoad_06->setGeometry(QRect(313, 477, 21, 31));
        pushRoad_07 = new QPushButton(centralWidget);
        pushRoad_07->setObjectName(QString::fromUtf8("pushRoad_07"));
        pushRoad_07->setGeometry(QRect(426, 285, 21, 31));
        pushRoad_08 = new QPushButton(centralWidget);
        pushRoad_08->setObjectName(QString::fromUtf8("pushRoad_08"));
        pushRoad_08->setGeometry(QRect(426, 477, 21, 31));
        pushRoad_09 = new QPushButton(centralWidget);
        pushRoad_09->setObjectName(QString::fromUtf8("pushRoad_09"));
        pushRoad_09->setGeometry(QRect(594, 185, 21, 31));
        pushRoad_10 = new QPushButton(centralWidget);
        pushRoad_10->setObjectName(QString::fromUtf8("pushRoad_10"));
        pushRoad_10->setGeometry(QRect(594, 379, 21, 31));
        pushRoad_11 = new QPushButton(centralWidget);
        pushRoad_11->setObjectName(QString::fromUtf8("pushRoad_11"));
        pushRoad_11->setGeometry(QRect(652, 285, 21, 31));
        pushRoad_12 = new QPushButton(centralWidget);
        pushRoad_12->setObjectName(QString::fromUtf8("pushRoad_12"));
        pushRoad_12->setGeometry(QRect(539, 477, 21, 31));
        pushRoad_13 = new QPushButton(centralWidget);
        pushRoad_13->setObjectName(QString::fromUtf8("pushRoad_13"));
        pushRoad_13->setGeometry(QRect(539, 285, 21, 31));
        pushRoad_14 = new QPushButton(centralWidget);
        pushRoad_14->setObjectName(QString::fromUtf8("pushRoad_14"));
        pushRoad_14->setGeometry(QRect(539, 93, 21, 31));
        pushRoad_16 = new QPushButton(centralWidget);
        pushRoad_16->setObjectName(QString::fromUtf8("pushRoad_16"));
        pushRoad_16->setGeometry(QRect(426, 93, 21, 31));
        pushRoad_17 = new QPushButton(centralWidget);
        pushRoad_17->setObjectName(QString::fromUtf8("pushRoad_17"));
        pushRoad_17->setGeometry(QRect(481, 185, 21, 31));
        pushRoad_18 = new QPushButton(centralWidget);
        pushRoad_18->setObjectName(QString::fromUtf8("pushRoad_18"));
        pushRoad_18->setGeometry(QRect(481, 379, 21, 31));
        pushRoad_19 = new QPushButton(centralWidget);
        pushRoad_19->setObjectName(QString::fromUtf8("pushRoad_19"));
        pushRoad_19->setGeometry(QRect(368, 185, 21, 31));
        pushRoad_20 = new QPushButton(centralWidget);
        pushRoad_20->setObjectName(QString::fromUtf8("pushRoad_20"));
        pushRoad_20->setGeometry(QRect(368, 379, 21, 31));
        pushRoad_21 = new QPushButton(centralWidget);
        pushRoad_21->setObjectName(QString::fromUtf8("pushRoad_21"));
        pushRoad_21->setGeometry(QRect(255, 379, 21, 31));
        pushRoad_22 = new QPushButton(centralWidget);
        pushRoad_22->setObjectName(QString::fromUtf8("pushRoad_22"));
        pushRoad_22->setGeometry(QRect(142, 379, 21, 31));
        pushRoad_23 = new QPushButton(centralWidget);
        pushRoad_23->setObjectName(QString::fromUtf8("pushRoad_23"));
        pushRoad_23->setGeometry(QRect(255, 185, 21, 31));
        pushRoad_24 = new QPushButton(centralWidget);
        pushRoad_24->setObjectName(QString::fromUtf8("pushRoad_24"));
        pushRoad_24->setGeometry(QRect(142, 185, 21, 31));
        pushRoad_25 = new QPushButton(centralWidget);
        pushRoad_25->setObjectName(QString::fromUtf8("pushRoad_25"));
        pushRoad_25->setGeometry(QRect(398, 43, 21, 31));
        pushRoad_26 = new QPushButton(centralWidget);
        pushRoad_26->setObjectName(QString::fromUtf8("pushRoad_26"));
        pushRoad_26->setGeometry(QRect(398, 141, 21, 31));
        pushRoad_27 = new QPushButton(centralWidget);
        pushRoad_27->setObjectName(QString::fromUtf8("pushRoad_27"));
        pushRoad_27->setGeometry(QRect(451, 141, 21, 31));
        pushRoad_28 = new QPushButton(centralWidget);
        pushRoad_28->setObjectName(QString::fromUtf8("pushRoad_28"));
        pushRoad_28->setGeometry(QRect(511, 141, 21, 31));
        pushRoad_29 = new QPushButton(centralWidget);
        pushRoad_29->setObjectName(QString::fromUtf8("pushRoad_29"));
        pushRoad_29->setGeometry(QRect(285, 43, 21, 31));
        pushRoad_30 = new QPushButton(centralWidget);
        pushRoad_30->setObjectName(QString::fromUtf8("pushRoad_30"));
        pushRoad_30->setGeometry(QRect(511, 43, 21, 31));
        pushRoad_31 = new QPushButton(centralWidget);
        pushRoad_31->setObjectName(QString::fromUtf8("pushRoad_31"));
        pushRoad_31->setGeometry(QRect(451, 43, 21, 31));
        pushRoad_32 = new QPushButton(centralWidget);
        pushRoad_32->setObjectName(QString::fromUtf8("pushRoad_32"));
        pushRoad_32->setGeometry(QRect(338, 43, 21, 31));
        pushRoad_33 = new QPushButton(centralWidget);
        pushRoad_33->setObjectName(QString::fromUtf8("pushRoad_33"));
        pushRoad_33->setGeometry(QRect(225, 43, 21, 31));
        pushRoad_34 = new QPushButton(centralWidget);
        pushRoad_34->setObjectName(QString::fromUtf8("pushRoad_34"));
        pushRoad_34->setGeometry(QRect(511, 235, 21, 31));
        pushRoad_35 = new QPushButton(centralWidget);
        pushRoad_35->setObjectName(QString::fromUtf8("pushRoad_35"));
        pushRoad_35->setGeometry(QRect(569, 235, 21, 31));
        pushRoad_36 = new QPushButton(centralWidget);
        pushRoad_36->setObjectName(QString::fromUtf8("pushRoad_36"));
        pushRoad_36->setGeometry(QRect(569, 141, 21, 31));
        pushRoad_37 = new QPushButton(centralWidget);
        pushRoad_37->setObjectName(QString::fromUtf8("pushRoad_37"));
        pushRoad_37->setGeometry(QRect(170, 141, 21, 31));
        pushRoad_38 = new QPushButton(centralWidget);
        pushRoad_38->setObjectName(QString::fromUtf8("pushRoad_38"));
        pushRoad_38->setGeometry(QRect(225, 141, 21, 31));
        pushRoad_39 = new QPushButton(centralWidget);
        pushRoad_39->setObjectName(QString::fromUtf8("pushRoad_39"));
        pushRoad_39->setGeometry(QRect(285, 141, 21, 31));
        pushRoad_40 = new QPushButton(centralWidget);
        pushRoad_40->setObjectName(QString::fromUtf8("pushRoad_40"));
        pushRoad_40->setGeometry(QRect(338, 141, 21, 31));
        pushRoad_41 = new QPushButton(centralWidget);
        pushRoad_41->setObjectName(QString::fromUtf8("pushRoad_41"));
        pushRoad_41->setGeometry(QRect(511, 525, 21, 31));
        pushRoad_42 = new QPushButton(centralWidget);
        pushRoad_42->setObjectName(QString::fromUtf8("pushRoad_42"));
        pushRoad_42->setGeometry(QRect(225, 427, 21, 31));
        pushRoad_43 = new QPushButton(centralWidget);
        pushRoad_43->setObjectName(QString::fromUtf8("pushRoad_43"));
        pushRoad_43->setGeometry(QRect(285, 427, 21, 31));
        pushRoad_44 = new QPushButton(centralWidget);
        pushRoad_44->setObjectName(QString::fromUtf8("pushRoad_44"));
        pushRoad_44->setGeometry(QRect(338, 427, 21, 31));
        pushRoad_45 = new QPushButton(centralWidget);
        pushRoad_45->setObjectName(QString::fromUtf8("pushRoad_45"));
        pushRoad_45->setGeometry(QRect(398, 427, 21, 31));
        pushRoad_46 = new QPushButton(centralWidget);
        pushRoad_46->setObjectName(QString::fromUtf8("pushRoad_46"));
        pushRoad_46->setGeometry(QRect(451, 427, 21, 31));
        pushRoad_47 = new QPushButton(centralWidget);
        pushRoad_47->setObjectName(QString::fromUtf8("pushRoad_47"));
        pushRoad_47->setGeometry(QRect(511, 427, 21, 31));
        pushRoad_48 = new QPushButton(centralWidget);
        pushRoad_48->setObjectName(QString::fromUtf8("pushRoad_48"));
        pushRoad_48->setGeometry(QRect(225, 525, 21, 31));
        pushRoad_49 = new QPushButton(centralWidget);
        pushRoad_49->setObjectName(QString::fromUtf8("pushRoad_49"));
        pushRoad_49->setGeometry(QRect(285, 525, 21, 31));
        pushRoad_50 = new QPushButton(centralWidget);
        pushRoad_50->setObjectName(QString::fromUtf8("pushRoad_50"));
        pushRoad_50->setGeometry(QRect(338, 525, 21, 31));
        pushRoad_51 = new QPushButton(centralWidget);
        pushRoad_51->setObjectName(QString::fromUtf8("pushRoad_51"));
        pushRoad_51->setGeometry(QRect(398, 525, 21, 31));
        pushRoad_52 = new QPushButton(centralWidget);
        pushRoad_52->setObjectName(QString::fromUtf8("pushRoad_52"));
        pushRoad_52->setGeometry(QRect(451, 525, 21, 31));
        pushRoad_53 = new QPushButton(centralWidget);
        pushRoad_53->setObjectName(QString::fromUtf8("pushRoad_53"));
        pushRoad_53->setGeometry(QRect(338, 333, 21, 31));
        pushRoad_54 = new QPushButton(centralWidget);
        pushRoad_54->setObjectName(QString::fromUtf8("pushRoad_54"));
        pushRoad_54->setGeometry(QRect(398, 333, 21, 31));
        pushRoad_55 = new QPushButton(centralWidget);
        pushRoad_55->setObjectName(QString::fromUtf8("pushRoad_55"));
        pushRoad_55->setGeometry(QRect(451, 333, 21, 31));
        pushRoad_56 = new QPushButton(centralWidget);
        pushRoad_56->setObjectName(QString::fromUtf8("pushRoad_56"));
        pushRoad_56->setGeometry(QRect(511, 333, 21, 31));
        pushRoad_57 = new QPushButton(centralWidget);
        pushRoad_57->setObjectName(QString::fromUtf8("pushRoad_57"));
        pushRoad_57->setGeometry(QRect(569, 333, 21, 31));
        pushRoad_58 = new QPushButton(centralWidget);
        pushRoad_58->setObjectName(QString::fromUtf8("pushRoad_58"));
        pushRoad_58->setGeometry(QRect(170, 427, 21, 31));
        pushRoad_59 = new QPushButton(centralWidget);
        pushRoad_59->setObjectName(QString::fromUtf8("pushRoad_59"));
        pushRoad_59->setGeometry(QRect(569, 427, 21, 31));
        pushRoad_60 = new QPushButton(centralWidget);
        pushRoad_60->setObjectName(QString::fromUtf8("pushRoad_60"));
        pushRoad_60->setGeometry(QRect(338, 235, 21, 31));
        pushRoad_61 = new QPushButton(centralWidget);
        pushRoad_61->setObjectName(QString::fromUtf8("pushRoad_61"));
        pushRoad_61->setGeometry(QRect(285, 235, 21, 31));
        pushRoad_62 = new QPushButton(centralWidget);
        pushRoad_62->setObjectName(QString::fromUtf8("pushRoad_62"));
        pushRoad_62->setGeometry(QRect(225, 235, 21, 31));
        pushRoad_63 = new QPushButton(centralWidget);
        pushRoad_63->setObjectName(QString::fromUtf8("pushRoad_63"));
        pushRoad_63->setGeometry(QRect(170, 235, 21, 31));
        pushRoad_64 = new QPushButton(centralWidget);
        pushRoad_64->setObjectName(QString::fromUtf8("pushRoad_64"));
        pushRoad_64->setGeometry(QRect(112, 235, 21, 31));
        pushRoad_65 = new QPushButton(centralWidget);
        pushRoad_65->setObjectName(QString::fromUtf8("pushRoad_65"));
        pushRoad_65->setGeometry(QRect(112, 333, 21, 31));
        pushRoad_66 = new QPushButton(centralWidget);
        pushRoad_66->setObjectName(QString::fromUtf8("pushRoad_66"));
        pushRoad_66->setGeometry(QRect(170, 333, 21, 31));
        pushRoad_67 = new QPushButton(centralWidget);
        pushRoad_67->setObjectName(QString::fromUtf8("pushRoad_67"));
        pushRoad_67->setGeometry(QRect(225, 333, 21, 31));
        pushRoad_68 = new QPushButton(centralWidget);
        pushRoad_68->setObjectName(QString::fromUtf8("pushRoad_68"));
        pushRoad_68->setGeometry(QRect(285, 333, 21, 31));
        pushRoad_69 = new QPushButton(centralWidget);
        pushRoad_69->setObjectName(QString::fromUtf8("pushRoad_69"));
        pushRoad_69->setGeometry(QRect(624, 235, 21, 31));
        pushRoad_70 = new QPushButton(centralWidget);
        pushRoad_70->setObjectName(QString::fromUtf8("pushRoad_70"));
        pushRoad_70->setGeometry(QRect(451, 235, 21, 31));
        pushRoad_71 = new QPushButton(centralWidget);
        pushRoad_71->setObjectName(QString::fromUtf8("pushRoad_71"));
        pushRoad_71->setGeometry(QRect(398, 235, 21, 31));
        pushRoad_72 = new QPushButton(centralWidget);
        pushRoad_72->setObjectName(QString::fromUtf8("pushRoad_72"));
        pushRoad_72->setGeometry(QRect(624, 330, 21, 31));
        catan_map->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(catan_map);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1000, 25));
        menuSample = new QMenu(menuBar);
        menuSample->setObjectName(QString::fromUtf8("menuSample"));
        catan_map->setMenuBar(menuBar);
        mainToolBar = new QToolBar(catan_map);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        catan_map->addToolBar(Qt::TopToolBarArea, mainToolBar);
        catan_map->insertToolBarBreak(mainToolBar);
        statusBar = new QStatusBar(catan_map);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        catan_map->setStatusBar(statusBar);

        menuBar->addAction(menuSample->menuAction());
        menuSample->addAction(actionWorks);

        retranslateUi(catan_map);

        QMetaObject::connectSlotsByName(catan_map);
    } // setupUi

    void retranslateUi(QMainWindow *catan_map)
    {
        catan_map->setWindowTitle(QApplication::translate("catan_map", "catan_map", 0, QApplication::UnicodeUTF8));
        actionWorks->setText(QApplication::translate("catan_map", "Works!!", 0, QApplication::UnicodeUTF8));
        image_label->setText(QString());
        pushButton_01->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_02->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_03->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_04->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_05->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_06->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_07->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_08->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_09->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_10->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_11->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_14->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_13->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_12->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_17->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_18->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_16->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_15->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_19->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_20->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_21->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_22->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_23->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_050->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_24->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_25->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_26->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_27->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_28->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_29->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_30->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_31->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_32->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_33->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_34->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_35->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_36->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_37->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_43->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_45->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_44->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_41->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_42->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_40->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_49->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_46->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_39->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_38->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_47->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_48->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_50->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_51->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_52->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushButton_53->setText(QApplication::translate("catan_map", "1", 0, QApplication::UnicodeUTF8));
        pushRoad_01->setText(QString());
        pushRoad_02->setText(QString());
        pushRoad_15->setText(QString());
        pushRoad_03->setText(QString());
        pushRoad_04->setText(QString());
        pushRoad_05->setText(QString());
        pushRoad_06->setText(QString());
        pushRoad_07->setText(QString());
        pushRoad_08->setText(QString());
        pushRoad_09->setText(QString());
        pushRoad_10->setText(QString());
        pushRoad_11->setText(QString());
        pushRoad_12->setText(QString());
        pushRoad_13->setText(QString());
        pushRoad_14->setText(QString());
        pushRoad_16->setText(QString());
        pushRoad_17->setText(QString());
        pushRoad_18->setText(QString());
        pushRoad_19->setText(QString());
        pushRoad_20->setText(QString());
        pushRoad_21->setText(QString());
        pushRoad_22->setText(QString());
        pushRoad_23->setText(QString());
        pushRoad_24->setText(QString());
        pushRoad_25->setText(QString());
        pushRoad_26->setText(QString());
        pushRoad_27->setText(QString());
        pushRoad_28->setText(QString());
        pushRoad_29->setText(QString());
        pushRoad_30->setText(QString());
        pushRoad_31->setText(QString());
        pushRoad_32->setText(QString());
        pushRoad_33->setText(QString());
        pushRoad_34->setText(QString());
        pushRoad_35->setText(QString());
        pushRoad_36->setText(QString());
        pushRoad_37->setText(QString());
        pushRoad_38->setText(QString());
        pushRoad_39->setText(QString());
        pushRoad_40->setText(QString());
        pushRoad_41->setText(QString());
        pushRoad_42->setText(QString());
        pushRoad_43->setText(QString());
        pushRoad_44->setText(QString());
        pushRoad_45->setText(QString());
        pushRoad_46->setText(QString());
        pushRoad_47->setText(QString());
        pushRoad_48->setText(QString());
        pushRoad_49->setText(QString());
        pushRoad_50->setText(QString());
        pushRoad_51->setText(QString());
        pushRoad_52->setText(QString());
        pushRoad_53->setText(QString());
        pushRoad_54->setText(QString());
        pushRoad_55->setText(QString());
        pushRoad_56->setText(QString());
        pushRoad_57->setText(QString());
        pushRoad_58->setText(QString());
        pushRoad_59->setText(QString());
        pushRoad_60->setText(QString());
        pushRoad_61->setText(QString());
        pushRoad_62->setText(QString());
        pushRoad_63->setText(QString());
        pushRoad_64->setText(QString());
        pushRoad_65->setText(QString());
        pushRoad_66->setText(QString());
        pushRoad_67->setText(QString());
        pushRoad_68->setText(QString());
        pushRoad_69->setText(QString());
        pushRoad_70->setText(QString());
        pushRoad_71->setText(QString());
        pushRoad_72->setText(QString());
        menuSample->setTitle(QApplication::translate("catan_map", "Sample", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class catan_map: public Ui_catan_map {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CATAN_MAP_H
